/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as NewInspectionRouteImport } from './routes/new-inspection'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIdRouteImport } from './routes/components.$id'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const NewInspectionRoute = NewInspectionRouteImport.update({
  id: '/new-inspection',
  path: '/new-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIdRoute = ComponentsIdRouteImport.update({
  id: '/components/$id',
  path: '/components/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fleet': typeof FleetRoute
  '/new-inspection': typeof NewInspectionRoute
  '/results': typeof ResultsRoute
  '/trends': typeof TrendsRoute
  '/components/$id': typeof ComponentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fleet': typeof FleetRoute
  '/new-inspection': typeof NewInspectionRoute
  '/results': typeof ResultsRoute
  '/trends': typeof TrendsRoute
  '/components/$id': typeof ComponentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fleet': typeof FleetRoute
  '/new-inspection': typeof NewInspectionRoute
  '/results': typeof ResultsRoute
  '/trends': typeof TrendsRoute
  '/components/$id': typeof ComponentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/fleet'
    | '/new-inspection'
    | '/results'
    | '/trends'
    | '/components/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/fleet'
    | '/new-inspection'
    | '/results'
    | '/trends'
    | '/components/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/fleet'
    | '/new-inspection'
    | '/results'
    | '/trends'
    | '/components/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  FleetRoute: typeof FleetRoute
  NewInspectionRoute: typeof NewInspectionRoute
  ResultsRoute: typeof ResultsRoute
  TrendsRoute: typeof TrendsRoute
  ComponentsIdRoute: typeof ComponentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-inspection': {
      id: '/new-inspection'
      path: '/new-inspection'
      fullPath: '/new-inspection'
      preLoaderRoute: typeof NewInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$id': {
      id: '/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof ComponentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  FleetRoute: FleetRoute,
  NewInspectionRoute: NewInspectionRoute,
  ResultsRoute: ResultsRoute,
  TrendsRoute: TrendsRoute,
  ComponentsIdRoute: ComponentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
